// Code generated by protoc-gen-go. DO NOT EDIT.
// source: information.proto

package io_stayhungrystayfoolish_github_grpcgo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DictionaryRequest struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Language             string   `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DictionaryRequest) Reset()         { *m = DictionaryRequest{} }
func (m *DictionaryRequest) String() string { return proto.CompactTextString(m) }
func (*DictionaryRequest) ProtoMessage()    {}
func (*DictionaryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f8c17226f3a67f1, []int{0}
}

func (m *DictionaryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DictionaryRequest.Unmarshal(m, b)
}
func (m *DictionaryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DictionaryRequest.Marshal(b, m, deterministic)
}
func (m *DictionaryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DictionaryRequest.Merge(m, src)
}
func (m *DictionaryRequest) XXX_Size() int {
	return xxx_messageInfo_DictionaryRequest.Size(m)
}
func (m *DictionaryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DictionaryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DictionaryRequest proto.InternalMessageInfo

func (m *DictionaryRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *DictionaryRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type DictionaryResponse struct {
	Dictionary           []*Dictionary `protobuf:"bytes,1,rep,name=dictionary,proto3" json:"dictionary,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DictionaryResponse) Reset()         { *m = DictionaryResponse{} }
func (m *DictionaryResponse) String() string { return proto.CompactTextString(m) }
func (*DictionaryResponse) ProtoMessage()    {}
func (*DictionaryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f8c17226f3a67f1, []int{1}
}

func (m *DictionaryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DictionaryResponse.Unmarshal(m, b)
}
func (m *DictionaryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DictionaryResponse.Marshal(b, m, deterministic)
}
func (m *DictionaryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DictionaryResponse.Merge(m, src)
}
func (m *DictionaryResponse) XXX_Size() int {
	return xxx_messageInfo_DictionaryResponse.Size(m)
}
func (m *DictionaryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DictionaryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DictionaryResponse proto.InternalMessageInfo

func (m *DictionaryResponse) GetDictionary() []*Dictionary {
	if m != nil {
		return m.Dictionary
	}
	return nil
}

type DictionaryPageRequest struct {
	Parent               string       `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Language             string       `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Page                 *PageRequest `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DictionaryPageRequest) Reset()         { *m = DictionaryPageRequest{} }
func (m *DictionaryPageRequest) String() string { return proto.CompactTextString(m) }
func (*DictionaryPageRequest) ProtoMessage()    {}
func (*DictionaryPageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f8c17226f3a67f1, []int{2}
}

func (m *DictionaryPageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DictionaryPageRequest.Unmarshal(m, b)
}
func (m *DictionaryPageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DictionaryPageRequest.Marshal(b, m, deterministic)
}
func (m *DictionaryPageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DictionaryPageRequest.Merge(m, src)
}
func (m *DictionaryPageRequest) XXX_Size() int {
	return xxx_messageInfo_DictionaryPageRequest.Size(m)
}
func (m *DictionaryPageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DictionaryPageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DictionaryPageRequest proto.InternalMessageInfo

func (m *DictionaryPageRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *DictionaryPageRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *DictionaryPageRequest) GetPage() *PageRequest {
	if m != nil {
		return m.Page
	}
	return nil
}

type DictionaryPageResponse struct {
	Content              map[string]*DictionaryResponse `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	First                bool                           `protobuf:"varint,2,opt,name=first,proto3" json:"first,omitempty"`
	Last                 bool                           `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"`
	TotalElements        int32                          `protobuf:"varint,4,opt,name=total_elements,json=totalElements,proto3" json:"total_elements,omitempty"`
	TotalPages           int32                          `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *DictionaryPageResponse) Reset()         { *m = DictionaryPageResponse{} }
func (m *DictionaryPageResponse) String() string { return proto.CompactTextString(m) }
func (*DictionaryPageResponse) ProtoMessage()    {}
func (*DictionaryPageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f8c17226f3a67f1, []int{3}
}

func (m *DictionaryPageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DictionaryPageResponse.Unmarshal(m, b)
}
func (m *DictionaryPageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DictionaryPageResponse.Marshal(b, m, deterministic)
}
func (m *DictionaryPageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DictionaryPageResponse.Merge(m, src)
}
func (m *DictionaryPageResponse) XXX_Size() int {
	return xxx_messageInfo_DictionaryPageResponse.Size(m)
}
func (m *DictionaryPageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DictionaryPageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DictionaryPageResponse proto.InternalMessageInfo

func (m *DictionaryPageResponse) GetContent() map[string]*DictionaryResponse {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *DictionaryPageResponse) GetFirst() bool {
	if m != nil {
		return m.First
	}
	return false
}

func (m *DictionaryPageResponse) GetLast() bool {
	if m != nil {
		return m.Last
	}
	return false
}

func (m *DictionaryPageResponse) GetTotalElements() int32 {
	if m != nil {
		return m.TotalElements
	}
	return 0
}

func (m *DictionaryPageResponse) GetTotalPages() int32 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

type ArticleRequest struct {
	DictName             string   `protobuf:"bytes,1,opt,name=dict_name,json=dictName,proto3" json:"dict_name,omitempty"`
	Language             string   `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleRequest) Reset()         { *m = ArticleRequest{} }
func (m *ArticleRequest) String() string { return proto.CompactTextString(m) }
func (*ArticleRequest) ProtoMessage()    {}
func (*ArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f8c17226f3a67f1, []int{4}
}

func (m *ArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleRequest.Unmarshal(m, b)
}
func (m *ArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleRequest.Marshal(b, m, deterministic)
}
func (m *ArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleRequest.Merge(m, src)
}
func (m *ArticleRequest) XXX_Size() int {
	return xxx_messageInfo_ArticleRequest.Size(m)
}
func (m *ArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleRequest proto.InternalMessageInfo

func (m *ArticleRequest) GetDictName() string {
	if m != nil {
		return m.DictName
	}
	return ""
}

func (m *ArticleRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type Dictionary struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Parent               string   `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Language             string   `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Display              bool     `protobuf:"varint,5,opt,name=display,proto3" json:"display,omitempty"`
	Icon                 string   `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`
	Url                  string   `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	Links                string   `protobuf:"bytes,8,opt,name=links,proto3" json:"links,omitempty"`
	Ordinal              int32    `protobuf:"varint,9,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Status               string   `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Extension            string   `protobuf:"bytes,11,opt,name=extension,proto3" json:"extension,omitempty"`
	Description          string   `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	CreatedBy            string   `protobuf:"bytes,13,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedDate          string   `protobuf:"bytes,14,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	LastModifiedBy       string   `protobuf:"bytes,15,opt,name=last_modified_by,json=lastModifiedBy,proto3" json:"last_modified_by,omitempty"`
	LastModifiedDate     string   `protobuf:"bytes,16,opt,name=last_modified_date,json=lastModifiedDate,proto3" json:"last_modified_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dictionary) Reset()         { *m = Dictionary{} }
func (m *Dictionary) String() string { return proto.CompactTextString(m) }
func (*Dictionary) ProtoMessage()    {}
func (*Dictionary) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f8c17226f3a67f1, []int{5}
}

func (m *Dictionary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dictionary.Unmarshal(m, b)
}
func (m *Dictionary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dictionary.Marshal(b, m, deterministic)
}
func (m *Dictionary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dictionary.Merge(m, src)
}
func (m *Dictionary) XXX_Size() int {
	return xxx_messageInfo_Dictionary.Size(m)
}
func (m *Dictionary) XXX_DiscardUnknown() {
	xxx_messageInfo_Dictionary.DiscardUnknown(m)
}

var xxx_messageInfo_Dictionary proto.InternalMessageInfo

func (m *Dictionary) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Dictionary) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Dictionary) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Dictionary) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Dictionary) GetDisplay() bool {
	if m != nil {
		return m.Display
	}
	return false
}

func (m *Dictionary) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Dictionary) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Dictionary) GetLinks() string {
	if m != nil {
		return m.Links
	}
	return ""
}

func (m *Dictionary) GetOrdinal() int32 {
	if m != nil {
		return m.Ordinal
	}
	return 0
}

func (m *Dictionary) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Dictionary) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

func (m *Dictionary) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Dictionary) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Dictionary) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *Dictionary) GetLastModifiedBy() string {
	if m != nil {
		return m.LastModifiedBy
	}
	return ""
}

func (m *Dictionary) GetLastModifiedDate() string {
	if m != nil {
		return m.LastModifiedDate
	}
	return ""
}

type Article struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DictId               int64    `protobuf:"varint,2,opt,name=dict_id,json=dictId,proto3" json:"dict_id,omitempty"`
	UniqueId             string   `protobuf:"bytes,3,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Text                 string   `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Language             string   `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	Display              bool     `protobuf:"varint,7,opt,name=display,proto3" json:"display,omitempty"`
	Icon                 string   `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	Thumbnail            string   `protobuf:"bytes,9,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Tag                  string   `protobuf:"bytes,10,opt,name=tag,proto3" json:"tag,omitempty"`
	Ordinal              int32    `protobuf:"varint,11,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Status               string   `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	Extension            string   `protobuf:"bytes,13,opt,name=extension,proto3" json:"extension,omitempty"`
	Description          string   `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	CreatedBy            string   `protobuf:"bytes,15,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedDate          string   `protobuf:"bytes,16,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	LastModifiedBy       string   `protobuf:"bytes,17,opt,name=last_modified_by,json=lastModifiedBy,proto3" json:"last_modified_by,omitempty"`
	LastModifiedDate     string   `protobuf:"bytes,18,opt,name=last_modified_date,json=lastModifiedDate,proto3" json:"last_modified_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f8c17226f3a67f1, []int{6}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Article) GetDictId() int64 {
	if m != nil {
		return m.DictId
	}
	return 0
}

func (m *Article) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Article) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Article) GetDisplay() bool {
	if m != nil {
		return m.Display
	}
	return false
}

func (m *Article) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Article) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

func (m *Article) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Article) GetOrdinal() int32 {
	if m != nil {
		return m.Ordinal
	}
	return 0
}

func (m *Article) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Article) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

func (m *Article) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Article) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Article) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *Article) GetLastModifiedBy() string {
	if m != nil {
		return m.LastModifiedBy
	}
	return ""
}

func (m *Article) GetLastModifiedDate() string {
	if m != nil {
		return m.LastModifiedDate
	}
	return ""
}

type PageRequest struct {
	PageNumber           int32    `protobuf:"varint,1,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Sort                 string   `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageRequest) Reset()         { *m = PageRequest{} }
func (m *PageRequest) String() string { return proto.CompactTextString(m) }
func (*PageRequest) ProtoMessage()    {}
func (*PageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f8c17226f3a67f1, []int{7}
}

func (m *PageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageRequest.Unmarshal(m, b)
}
func (m *PageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageRequest.Marshal(b, m, deterministic)
}
func (m *PageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageRequest.Merge(m, src)
}
func (m *PageRequest) XXX_Size() int {
	return xxx_messageInfo_PageRequest.Size(m)
}
func (m *PageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PageRequest proto.InternalMessageInfo

func (m *PageRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *PageRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PageRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func init() {
	proto.RegisterType((*DictionaryRequest)(nil), "DictionaryRequest")
	proto.RegisterType((*DictionaryResponse)(nil), "DictionaryResponse")
	proto.RegisterType((*DictionaryPageRequest)(nil), "DictionaryPageRequest")
	proto.RegisterType((*DictionaryPageResponse)(nil), "DictionaryPageResponse")
	proto.RegisterMapType((map[string]*DictionaryResponse)(nil), "DictionaryPageResponse.ContentEntry")
	proto.RegisterType((*ArticleRequest)(nil), "ArticleRequest")
	proto.RegisterType((*Dictionary)(nil), "Dictionary")
	proto.RegisterType((*Article)(nil), "Article")
	proto.RegisterType((*PageRequest)(nil), "PageRequest")
}

func init() { proto.RegisterFile("information.proto", fileDescriptor_1f8c17226f3a67f1) }

var fileDescriptor_1f8c17226f3a67f1 = []byte{
	// 829 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdf, 0x6f, 0xe3, 0x44,
	0x10, 0x6e, 0x7e, 0x3b, 0xe3, 0x34, 0x4d, 0x17, 0xe8, 0x59, 0xe1, 0x80, 0x60, 0x01, 0x0a, 0x82,
	0xf3, 0x43, 0x78, 0x41, 0x3c, 0x70, 0xba, 0xd2, 0x13, 0xaa, 0x10, 0x07, 0xf2, 0x3d, 0x20, 0x21,
	0xa1, 0x68, 0x63, 0x6f, 0xd3, 0xe5, 0xec, 0xdd, 0xdc, 0xee, 0xba, 0x3a, 0xf3, 0xaf, 0xf0, 0xc4,
	0x3f, 0xc3, 0xbf, 0x05, 0x9a, 0x5d, 0x3b, 0x75, 0xae, 0x09, 0x3d, 0x74, 0x6f, 0x33, 0xdf, 0x4c,
	0xbf, 0x9d, 0xce, 0xf7, 0x65, 0x0c, 0xa7, 0x5c, 0x5c, 0x49, 0x95, 0x53, 0xc3, 0xa5, 0x88, 0x36,
	0x4a, 0x1a, 0x19, 0x7e, 0x0f, 0xa7, 0x17, 0x3c, 0x41, 0x80, 0xaa, 0x32, 0x66, 0x2f, 0x0b, 0xa6,
	0x0d, 0x39, 0x83, 0xfe, 0x86, 0x2a, 0x26, 0x4c, 0xd0, 0x9a, 0xb5, 0xe6, 0xc3, 0xb8, 0xca, 0xc8,
	0x14, 0xbc, 0x8c, 0x8a, 0x75, 0x41, 0xd7, 0x2c, 0x68, 0xdb, 0xca, 0x36, 0x0f, 0x9f, 0x00, 0x69,
	0x12, 0xe9, 0x8d, 0x14, 0x9a, 0x91, 0x2f, 0x00, 0xd2, 0x2d, 0x1a, 0xb4, 0x66, 0x9d, 0xb9, 0xbf,
	0xf0, 0xa3, 0x46, 0x63, 0xa3, 0x1c, 0xe6, 0xf0, 0xde, 0x6d, 0xe5, 0x67, 0xba, 0x66, 0x6f, 0x31,
	0x0f, 0x99, 0x41, 0x77, 0x83, 0x78, 0x67, 0xd6, 0x9a, 0xfb, 0x8b, 0x51, 0xd4, 0xe0, 0x8b, 0x6d,
	0x25, 0xfc, 0xb3, 0x0d, 0x67, 0xaf, 0xbf, 0x57, 0x8d, 0xfd, 0x2d, 0x0c, 0x12, 0x29, 0x8c, 0x7b,
	0x11, 0x67, 0xfe, 0x24, 0xda, 0xdf, 0x19, 0x7d, 0xe7, 0xda, 0x9e, 0x0a, 0xa3, 0xca, 0xb8, 0xfe,
	0x23, 0xf2, 0x2e, 0xf4, 0xae, 0xb8, 0xd2, 0xc6, 0x4e, 0xe5, 0xc5, 0x2e, 0x21, 0x04, 0xba, 0x19,
	0xd5, 0xc6, 0x8e, 0xe4, 0xc5, 0x36, 0x26, 0x9f, 0xc2, 0xd8, 0x48, 0x43, 0xb3, 0x25, 0xcb, 0x58,
	0xce, 0x84, 0xd1, 0x41, 0x77, 0xd6, 0x9a, 0xf7, 0xe2, 0x63, 0x8b, 0x3e, 0xad, 0x40, 0xf2, 0x11,
	0xf8, 0xae, 0x0d, 0x27, 0xd7, 0x41, 0xcf, 0xf6, 0x80, 0x85, 0x70, 0x1c, 0x3d, 0xfd, 0x09, 0x46,
	0xcd, 0x51, 0xc8, 0x04, 0x3a, 0x2f, 0x58, 0x59, 0xed, 0x0b, 0x43, 0xf2, 0x39, 0xf4, 0x6e, 0x68,
	0x56, 0xb8, 0x4d, 0xf9, 0x8b, 0x77, 0xa2, 0xbb, 0x72, 0xc5, 0xae, 0xe3, 0x9b, 0xf6, 0xd7, 0xad,
	0xf0, 0x12, 0xc6, 0x4f, 0x94, 0xe1, 0x49, 0xb6, 0x55, 0xe1, 0x7d, 0x18, 0xa2, 0x58, 0x4b, 0x41,
	0x73, 0x56, 0x11, 0x7b, 0x08, 0x3c, 0xa3, 0x39, 0xfb, 0x4f, 0x6b, 0xfc, 0xdd, 0x01, 0xb8, 0x7d,
	0x8c, 0x8c, 0xa1, 0xcd, 0x53, 0x4b, 0xd0, 0x89, 0xdb, 0x3c, 0x6d, 0xa8, 0xdb, 0xde, 0x51, 0x97,
	0x40, 0xd7, 0x3e, 0xd5, 0xb1, 0xa8, 0x8d, 0x77, 0x9e, 0xe9, 0xbe, 0xa6, 0x78, 0x00, 0x83, 0x94,
	0xeb, 0x4d, 0x46, 0x4b, 0xbb, 0x1f, 0x2f, 0xae, 0x53, 0x64, 0xe2, 0x89, 0x14, 0x41, 0xdf, 0x31,
	0x61, 0x8c, 0x0b, 0x2a, 0x54, 0x16, 0x0c, 0xdc, 0x82, 0x0a, 0x95, 0xa1, 0x68, 0x19, 0x17, 0x2f,
	0x74, 0xe0, 0x59, 0xcc, 0x25, 0xc8, 0x2a, 0x55, 0xca, 0x05, 0xcd, 0x82, 0xa1, 0xdd, 0x7a, 0x9d,
	0xe2, 0xdc, 0xda, 0x50, 0x53, 0xe8, 0x00, 0xdc, 0xdc, 0x2e, 0x23, 0x0f, 0x61, 0xc8, 0x5e, 0x19,
	0x26, 0x34, 0x97, 0x22, 0xf0, 0x6d, 0xe9, 0x16, 0x20, 0x33, 0xf0, 0x53, 0xa6, 0x13, 0xc5, 0x37,
	0xb8, 0x8f, 0x60, 0x64, 0xeb, 0x4d, 0x88, 0x7c, 0x00, 0x90, 0x28, 0x46, 0x0d, 0x4b, 0x97, 0xab,
	0x32, 0x38, 0x76, 0x04, 0x15, 0x72, 0x5e, 0x92, 0x8f, 0x61, 0x54, 0x97, 0x53, 0x6a, 0x58, 0x30,
	0x76, 0x0c, 0x15, 0x76, 0x41, 0x0d, 0x23, 0x73, 0x98, 0xa0, 0xb9, 0x96, 0xb9, 0x4c, 0xf9, 0x15,
	0x77, 0x3c, 0x27, 0xb6, 0x6d, 0x8c, 0xf8, 0x8f, 0x15, 0x7c, 0x5e, 0x92, 0x2f, 0x81, 0xec, 0x76,
	0x5a, 0xca, 0x89, 0xed, 0x9d, 0x34, 0x7b, 0x91, 0x37, 0xfc, 0xa7, 0x03, 0x83, 0xca, 0x14, 0x77,
	0x54, 0x7c, 0x80, 0xdb, 0x4f, 0xcc, 0x92, 0xa7, 0x56, 0xc6, 0x4e, 0xdc, 0xc7, 0xf4, 0x32, 0x45,
	0xdb, 0x14, 0x82, 0xbf, 0x2c, 0x18, 0x96, 0x9c, 0x96, 0x9e, 0x03, 0x2e, 0x53, 0xdc, 0xb9, 0xe1,
	0x26, 0xab, 0xc5, 0x74, 0x09, 0xea, 0x65, 0xd8, 0x2b, 0x63, 0x65, 0x1c, 0xc6, 0x36, 0xde, 0x51,
	0xbe, 0x7f, 0x58, 0xf9, 0xc1, 0x7e, 0xe5, 0xbd, 0x86, 0xf2, 0x0f, 0x61, 0x68, 0xae, 0x8b, 0x7c,
	0x25, 0x28, 0x77, 0x9a, 0x0e, 0xe3, 0x5b, 0x00, 0x7d, 0x61, 0xe8, 0xba, 0x92, 0x14, 0xc3, 0xa6,
	0x03, 0xfc, 0x43, 0x0e, 0x18, 0x1d, 0x76, 0xc0, 0xf1, 0x3d, 0x0e, 0x18, 0xdf, 0xe7, 0x80, 0x93,
	0xfb, 0x1c, 0x30, 0x79, 0x33, 0x07, 0x9c, 0xfe, 0x0f, 0x07, 0x90, 0x03, 0x0e, 0xf8, 0x0d, 0xfc,
	0xe6, 0x61, 0xfe, 0x10, 0x00, 0x0f, 0xd2, 0xb3, 0x22, 0x5f, 0x31, 0x65, 0xcd, 0xd0, 0x8b, 0x1b,
	0x08, 0x8a, 0x86, 0xd9, 0x73, 0xfe, 0x87, 0xbb, 0x0a, 0xbd, 0x78, 0x9b, 0xa3, 0x34, 0x5a, 0x2a,
	0x53, 0xff, 0xbc, 0x31, 0x5e, 0xfc, 0xd5, 0x6a, 0x7e, 0x8e, 0x9e, 0x33, 0x75, 0xc3, 0x13, 0x46,
	0x1e, 0x03, 0xd1, 0x2c, 0x63, 0x89, 0x91, 0xaa, 0x71, 0x46, 0x48, 0x74, 0xe7, 0xc3, 0x35, 0xdd,
	0x77, 0xd4, 0xc2, 0x23, 0xf2, 0x03, 0x9c, 0xdd, 0x25, 0xc0, 0xff, 0x83, 0x9c, 0x45, 0x7b, 0xbf,
	0x38, 0xd3, 0x07, 0x07, 0xee, 0x7d, 0x78, 0xb4, 0x78, 0xbc, 0x3d, 0x8c, 0xf5, 0x7c, 0x8f, 0x60,
	0x4c, 0x1d, 0x72, 0xc1, 0x0c, 0xe5, 0x99, 0x26, 0x27, 0xd1, 0xee, 0xed, 0x9c, 0x7a, 0x35, 0x10,
	0x1e, 0x9d, 0xff, 0x02, 0x8f, 0xb8, 0x8c, 0xb4, 0xa1, 0xe5, 0x75, 0x21, 0xd6, 0xaa, 0xc4, 0xe8,
	0x4a, 0xca, 0x8c, 0xeb, 0xeb, 0x68, 0xcd, 0xcd, 0x75, 0xb1, 0x8a, 0xd6, 0x6a, 0x93, 0xfc, 0x4e,
	0x6f, 0xa8, 0x0d, 0x7e, 0xfd, 0xec, 0x4d, 0xda, 0xd7, 0x72, 0xd5, 0xb7, 0x9f, 0xf4, 0xaf, 0xfe,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0x99, 0x06, 0xcd, 0xc5, 0xe7, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DictionaryServiceClient is the client API for DictionaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DictionaryServiceClient interface {
	SelectorDictionary(ctx context.Context, in *DictionaryRequest, opts ...grpc.CallOption) (*DictionaryResponse, error)
	SelectorDictionaryPage(ctx context.Context, in *DictionaryPageRequest, opts ...grpc.CallOption) (*DictionaryPageResponse, error)
}

type dictionaryServiceClient struct {
	cc *grpc.ClientConn
}

func NewDictionaryServiceClient(cc *grpc.ClientConn) DictionaryServiceClient {
	return &dictionaryServiceClient{cc}
}

func (c *dictionaryServiceClient) SelectorDictionary(ctx context.Context, in *DictionaryRequest, opts ...grpc.CallOption) (*DictionaryResponse, error) {
	out := new(DictionaryResponse)
	err := c.cc.Invoke(ctx, "/DictionaryService/selectorDictionary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictionaryServiceClient) SelectorDictionaryPage(ctx context.Context, in *DictionaryPageRequest, opts ...grpc.CallOption) (*DictionaryPageResponse, error) {
	out := new(DictionaryPageResponse)
	err := c.cc.Invoke(ctx, "/DictionaryService/selectorDictionaryPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DictionaryServiceServer is the server API for DictionaryService service.
type DictionaryServiceServer interface {
	SelectorDictionary(context.Context, *DictionaryRequest) (*DictionaryResponse, error)
	SelectorDictionaryPage(context.Context, *DictionaryPageRequest) (*DictionaryPageResponse, error)
}

func RegisterDictionaryServiceServer(s *grpc.Server, srv DictionaryServiceServer) {
	s.RegisterService(&_DictionaryService_serviceDesc, srv)
}

func _DictionaryService_SelectorDictionary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictionaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServiceServer).SelectorDictionary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DictionaryService/SelectorDictionary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServiceServer).SelectorDictionary(ctx, req.(*DictionaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictionaryService_SelectorDictionaryPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictionaryPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServiceServer).SelectorDictionaryPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DictionaryService/SelectorDictionaryPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServiceServer).SelectorDictionaryPage(ctx, req.(*DictionaryPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DictionaryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DictionaryService",
	HandlerType: (*DictionaryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "selectorDictionary",
			Handler:    _DictionaryService_SelectorDictionary_Handler,
		},
		{
			MethodName: "selectorDictionaryPage",
			Handler:    _DictionaryService_SelectorDictionaryPage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "information.proto",
}

// ArticleServiceClient is the client API for ArticleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArticleServiceClient interface {
	ArticleDetails(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*Article, error)
}

type articleServiceClient struct {
	cc *grpc.ClientConn
}

func NewArticleServiceClient(cc *grpc.ClientConn) ArticleServiceClient {
	return &articleServiceClient{cc}
}

func (c *articleServiceClient) ArticleDetails(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*Article, error) {
	out := new(Article)
	err := c.cc.Invoke(ctx, "/ArticleService/articleDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServiceServer is the server API for ArticleService service.
type ArticleServiceServer interface {
	ArticleDetails(context.Context, *ArticleRequest) (*Article, error)
}

func RegisterArticleServiceServer(s *grpc.Server, srv ArticleServiceServer) {
	s.RegisterService(&_ArticleService_serviceDesc, srv)
}

func _ArticleService_ArticleDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).ArticleDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ArticleService/ArticleDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).ArticleDetails(ctx, req.(*ArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ArticleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ArticleService",
	HandlerType: (*ArticleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "articleDetails",
			Handler:    _ArticleService_ArticleDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "information.proto",
}
